% -------------------------------------------------------------------
%  Generated by MATLAB on 3-Oct-2020 13:38:09
%  MATLAB version: 9.2.0.538062 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('ex1.mat');

I = saveVarsMat.I; % <400x1400x3 uint8> too many elements

change = saveVarsMat.change; % <31x73x3 double> too many elements

decorr = saveVarsMat.decorr; % <31x73x3 double> too many elements

im4 = saveVarsMat.im4; % <31x73x3 double> too many elements

clear saveVarsMat;
